"""Persistent game project memory.

Stored in <Project>/AIGameBuilder/project.json (source of truth, outside Content so it is not an asset and is easy to
diff in source control). A readable GameDesign.md is regenerated next to it after every change.
"""

import datetime
import json
import os
import pathlib

import unreal

SCHEMA_VERSION = 1

# Recommended design document sections, in display order. Other keys are allowed and shown after these.
DESIGN_SECTIONS = {
    'overview': 'Overview (pitch, genre, pillars)',
    'setting': 'Setting & story',
    'player_experience': 'Player experience (core loop, session, goals)',
    'systems': 'Gameplay systems',
    'world': 'World & levels',
    'progression': 'Progression & economy',
    'multiplayer': 'Multiplayer',
    'art_audio': 'Art & audio direction',
    'ui_controls': 'UI & controls',
    'platforms': 'Platforms, business & release',
    'scope': 'Scope & milestones',
}

TASK_STATUSES = ('todo', 'doing', 'done', 'blocked')
ASSET_STATUSES = ('needed', 'placeholder', 'provided')
PACK_STATUSES = ('suggested', 'added', 'skipped')
PACK_PRIORITIES = ('essential', 'recommended', 'optional')
DECISION_SOURCES = ('user', 'ai_default')


def _now() -> str:
    return datetime.datetime.now().replace(microsecond=0).isoformat(sep=' ')


def memory_dir() -> pathlib.Path:
    project = unreal.Paths.convert_relative_path_to_full(unreal.Paths.project_dir())
    return pathlib.Path(project) / 'AIGameBuilder'


def _project_file() -> pathlib.Path:
    return memory_dir() / 'project.json'


def _empty() -> dict:
    return {
        'schemaVersion': SCHEMA_VERSION,
        'game': {},
        'design': {},
        'decisions': [],
        'tasks': [],
        'assets': [],
        'packs': [],
    }


def exists() -> bool:
    return _project_file().exists()


def load() -> dict:
    path = _project_file()
    if not path.exists():
        return _empty()
    data = json.loads(path.read_text(encoding='utf-8'))
    for key, value in _empty().items():
        data.setdefault(key, value)
    return data


def save(data: dict) -> None:
    folder = memory_dir()
    folder.mkdir(parents=True, exist_ok=True)
    data.setdefault('game', {})['updated'] = _now()
    tmp = folder / 'project.json.tmp'
    tmp.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding='utf-8')
    os.replace(tmp, _project_file())
    (folder / 'GameDesign.md').write_text(render_markdown(data), encoding='utf-8')


def next_id(items: list, prefix: str) -> str:
    highest = 0
    for item in items:
        try:
            highest = max(highest, int(str(item.get('id', '')).split('-')[-1]))
        except ValueError:
            pass
    return f'{prefix}-{highest + 1:03d}'


def section_title(key: str) -> str:
    return DESIGN_SECTIONS.get(key, key.replace('_', ' ').capitalize())


def ordered_sections(design: dict) -> list:
    known = [k for k in DESIGN_SECTIONS if k in design]
    extra = sorted(k for k in design if k not in DESIGN_SECTIONS)
    return known + extra


def active_decisions(data: dict) -> list:
    return [d for d in data['decisions'] if not d.get('supersededBy')]


def render_markdown(data: dict) -> str:
    game = data.get('game', {})
    lines = [f"# {game.get('name', 'Untitled game')} — Game Design",
             '',
             f"_Genre: {game.get('genre', '?')} · Created {game.get('created', '?')} · Updated {game.get('updated', '?')}_",
             '',
             '> Generated by AI World Builder from AIGameBuilder/project.json — edit through the AI (GameDesignTools), '
             'or edit project.json and ask the AI to reload.',
             '']
    if game.get('pitch'):
        lines += ['## Pitch', '', game['pitch'], '']

    for key in ordered_sections(data['design']):
        lines += [f'## {section_title(key)}', '', data['design'][key].strip(), '']

    decisions = active_decisions(data)
    if decisions:
        lines += ['## Decision log', '', '| ID | Topic | Choice | By | Why |', '|---|---|---|---|---|']
        for d in decisions:
            by = 'You' if d['source'] == 'user' else 'AI default (change any time)'
            lines.append(f"| {d['id']} | {d['topic']} | {d['choice']} | {by} | {d.get('rationale', '')} |")
        lines.append('')

    if data['tasks']:
        lines += ['## Task board', '']
        milestones = []
        for t in data['tasks']:
            if t['milestone'] not in milestones:
                milestones.append(t['milestone'])
        for m in milestones:
            tasks = [t for t in data['tasks'] if t['milestone'] == m]
            done = sum(1 for t in tasks if t['status'] == 'done')
            lines += [f'### {m} ({done}/{len(tasks)} done)', '']
            for t in tasks:
                box = {'done': 'x', 'doing': '~', 'blocked': '!'}.get(t['status'], ' ')
                note = f" — {t['notes']}" if t.get('notes') else ''
                lines.append(f"- [{box}] {t['id']} {t['title']}{note}")
            lines.append('')

    if data['assets']:
        lines += ['## Asset wishlist', '', '| ID | Asset | Category | Purpose | Status | Path / placeholder |',
                  '|---|---|---|---|---|---|']
        for a in data['assets']:
            where = a.get('path') or a.get('placeholder') or ''
            lines.append(f"| {a['id']} | {a['name']} | {a['category']} | {a.get('purpose', '')} | {a['status']} | {where} |")
        lines.append('')

    if data.get('packs'):
        lines += ['## Asset packs to add (Fab / Marketplace)', '',
                  'Add these in the editor (Fab: find the pack, "Add to Project"), then tell the AI which ones you added.', '',
                  '| ID | Pack | Priority | Search for | Why | Must have | Status |', '|---|---|---|---|---|---|---|']
        order = {p: i for i, p in enumerate(PACK_PRIORITIES)}
        for k in sorted(data['packs'], key=lambda k: (order.get(k['priority'], 9), k['id'])):
            status = k['status'] + (f" ({k['path']})" if k.get('path') else '')
            lines.append(f"| {k['id']} | {k['name']} | {k['priority']} | {k.get('search', '')} | {k.get('why', '')} | "
                         f"{k.get('requirements', '')} | {status} |")
        lines.append('')
    return '\n'.join(lines)
